name: Run Node.js app with MongoDB

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run app
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: node js/server.js
